apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-tracer
  labels:
    app: minio-tracer
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
      matchLabels:
        app: minio-tracer
  template:
    metadata:
      labels:
        app: minio-tracer
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: minio-tracer
      containers:
      - name: minio-tracer
        image: "{{IMAGE}}"
        imagePullPolicy: Always
        env:
        - name: TRACE_SECRET
          value: "{{ .Values.secretName }}"
        - name: TRACE_SERVICE
          value: "{{ .Values.serviceName }}"
