name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: olegtarasov/get-tag@v2
      id: tagName

    ‐ name: Publish Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        repository: rubenv/minio-tracer
        tags: ${{ steps.tagName.outputs.tag }}

    - name: Package and publish chart
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE: docker.io/rubenv/minio-tracer: ${{ steps.tagName.outputs.tag }}
        VERSION: ${{ steps.tagName.outputs.tag }}
      run: |
          mkdir -p /tmp/out
          sed -i -e "s,{{IMAGE}},$IMAGE," helm/minio-tracer/templates/deployment.yaml
          sed -i -e "s,{{VERSION}},$VERSION," helm/minio-tracer/Chart.yaml
          helm package -d /tmp/out ./helm/minio-tracer
          git checkout .

          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch
          git checkout gh-pages
          cp /tmp/out/* .
          helm repo index .
          git config user.name "Robot"
          git config user.email "robot@rocketeer.be"
          git add .
          git commit -a -m "Update chart repository"
          git push

